---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/shbtrave/leavetools.shbtravel.vn/
    - /bin/cp -r ./application $DEPLOYPATH
    - /bin/cp -r ./assets $DEPLOYPATH
    - /bin/cp -r ./docker $DEPLOYPATH
    - /bin/cp -r ./local $DEPLOYPATH
    - /bin/cp -r ./system $DEPLOYPATH