version: '3.4'
services:
  jorani:
    build: .
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=jorani
      - MYSQL_USER=jorani
      - MYSQL_PASSWORD=jorani
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=jorani
      - MYSQL_DATABASE=jorani
      - MYSQL_USER=jorani
      - MYSQL_PASSWORD=jorani
    volumes:
      - ./sql/jorani.sql:/docker-entrypoint-initdb.d/jorani.sql
